== FAQ

Ich empfange mit einem e160 huwaei Schlüssel nichts.::
Sie müssen minicom installieren (sudo apt-get install -y minicom ), starten Sie es und verbinden sich mit dem Modem, dann machen Sie folgendes : 

[source,bash]
AT^CURC=0
AT^U2DIAG=0

Und auf dem Plugin machen Sie : 

- Wählen Sie den ersten USB-Port, nicht den zweiten
- Geschwindigkeit : 9600
- Text-Modus deaktivieren

'''

Ich sehe den USB-Anschluss meines Schlüssel nicht::
Überprüfen Sie, dass Sie brltty nicht installiert haben (`sudo apt-get remove brltty` um es zu löschen)

'''

Nach einigen Stunden/Tage erhalte ich kein SMS mehr und kann nicht mehr senden, verbessert das eine Wiederbelebung des Dämons::
Überprüfen Sie Ihre USB-Kabel (ein defektes USB Kabel sorgt häufig für diese Art von Problemen, es darf auch nicht zu lang sein), überprüfen Sie auch Ihre Stromversorgung, ein USB-Hub wird dringend empfohlen

'''

Ich habe einen CME XX Fehler::
link::http://www.micromedia-int.com/fr/gsm-2/669-cme-error-gsm-equipment-related-errors[Hier] finden Sie die Beschreibung der verschiedenen CME Fehler.

'''

Konfiguration des Alcatel one-Touch-X220L Schlüssels::
Wenn man den Schlüssel einfügt, macht man dies :

[source,bash]
root@jeedom:# lsusb
Bus 002 Device 003: ID 1bbb:f000 T & A Mobile Phones

Achtung, wenn Sie 1bbb:f000 nicht haben, darf man vor allem dieser Dokumentation nicht folgen

Sie müssen die folgenden Zeilen am Ende der Datei hinzufügen /etc/usb_modeswitch.conf :

[source,bash]
########################################################
# Alcatel X220L
DefaultVendor= 0x1bbb
DefaultProduct= 0xf000
MessageContent="55534243123456788000000080000606f50402527000000000000000000000"
########################################################

Dann starten Sie den folgenden Befehl zum Test :

[source,bash]
/usr/sbin/usb_modeswitch -c
/etc/usb_modeswitch.conf

Wir erhalten folgendes :

[source,bash]
root@jeedom:~# lsusb
Bus 002 Device 003: ID 1bbb:0017 T & A Mobile Phones

und die Links unter  /dev werden hinzugefügt :

[source,bash]
root@jeedom:~# ls /dev/ttyUSB*
/dev/ttyUSB0 /dev/ttyUSB1 /dev/ttyUSB2 /dev/ttyUSB3 /dev/ttyUSB4

Nun müssen wir den Start des vorherigen Befehls über udev automatisieren :

[source,bash]
root@jeedom:# vi /etc/udev/rules.d99-usb_modeswitch.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="1bbb", ATTRS{idProduct}=="f000", RUN+="/usr/sbin/usb_modeswitch -c /etc/usb_modeswitch.conf"

Sous jeedom dans le plugin SMS, il faut (dans mon cas) utiliser le "port SMS" suivant : /dev/ttyUSB3. En gros il faut essayer chaque port pour trouver le bon…​

'''

Le démons SMS est bien démarré, mais vous ne recevez aucun SMS::
Une des causes probables est la mauvaise configuration réseau. Dans "Général" > "Configuration" > "Administration" > "Configuration réseaux", vérifier le contenu du champ "Adresse URL ou IP".

Ce dernier ne doit pas être localhost ou 127.0.0.1 mais l'adresse IP de votre Jeedom ou son nom DNS.

En cas de l'utilisation du plugin SMS sur un esclave Jeedom en mode déporté, vérifier aussi la configuration de ce dernier.

'''

En mode debug j'ai l'erreur "timeout" qui apparaît::
Cette erreur arrive quand la clef ne répond pas dans les 10 secondes qui suivent une demande. Les causes connues peuvent être :

- incompatibilité de la clef GSM,
- problème avec la version du firmware de la clef.

'''

Lors du démarrage en mode debug j'ai : "socket already in use"::
Cela veut dire que le démon est démarré mais que Jeedom n'arrive pas à le stopper. Vous pouvez soit redémarrer tout le système, soit en SSH faire "killall -9 refxcmd.py".

'''

Le démon refuse de démarrer::
Essayez de le démarrer en mode debug pour voir l'erreur.

'''

J'ai plusieurs port USB pour ma clef GSM alors que je n'en ai qu'une::
C'est normal, pour une raison inconnue les clef GSM créent 2 (et même plus) ports USB au niveau système. Il suffit d'en choisir un, peut importe lequel.

'''

Jeedom n'envoie plus et ne reçoit plus de SMS::
Ceci arrive en général si la clef GSM n'arrive plus à se connecter au réseau. Essayer de la déplacer et de voir si ça revient au bout de quelques minutes.