[panel,danger]
.Le démon refuse de démarrer...
--
Essayez de le démarrer en mode debug pour voir l'erreur.
--

[panel,danger]
.Lors du démarrage en mode debug j'ai : "socket already in use"...
--
Cela veut dire que le démon est démarré mais que Jeedom n'arrive pas à le stopper. Vous pouvez soit redémarrer tout le système, soit en ssh faire "killall -9 refxcmd.py".
--

[panel,danger]
.En mode debug j'ai l'erreur "timeout" qui apparaît...
--
Cette erreur arrive quand la clef ne répond pas dans les 10 secondes qui suivent une demande. Les causes connues peuvent être :

** incompatibilité de la clef GSM,
** problème avec la version du firmware de la clef.
--

[panel,danger]
.Le démons SMS est bien démarré, mais vous ne recevez aucun SMS
--
Une des cause probable, est la mauvaise configuration réseau. Dans "Général" > "Configuration" > "Administration" > "Configuration réseaux", vérifier le contenu du champ "Adresse URL ou IP".

Ce dernier ne doit pas être localhost ou 127.0.0.1 mais l'adresse IP de votre Jeedom ou son nom DNS.

En cas de l'utilisation du plugin SMS sur un esclave Jeedom en mode déporter, vérifier aussi la configuration de ce dernier.
--

[panel,danger]
.Configuration de la clef Alcatel one touch X220L
--
Lorsque l'on insère la clef, on a ceci :
----
root@jeedom:# lsusb
Bus 002 Device 003: ID 1bbb:f000 T & A Mobile Phones
----

*Attention* si vous n'avez pas 1bbb:f000 il ne faut surtout pas faire la suite de cette documentation

il faut ajouter les lignes suivantes à la fin du fichier /etc/usb_modeswitch.conf :
----
########################################################
# Alcatel X220L

DefaultVendor= 0x1bbb
DefaultProduct= 0xf000

MessageContent="55534243123456788000000080000606f50402527000000000000000000000"
########################################################
----

Puis lancer la commande suivante pour tester :
----
/usr/sbin/usb_modeswitch -c /etc/usb_modeswitch.conf
----

On obtient ceci :
----
root@jeedom:~# lsusb
Bus 002 Device 003: ID 1bbb:0017 T & A Mobile Phones
----

et les liens sous /dev sont bien ajoutés :
----
root@jeedom:~# ls /dev/ttyUSB*
/dev/ttyUSB0 /dev/ttyUSB1 /dev/ttyUSB2 /dev/ttyUSB3 /dev/ttyUSB4
-----

Maintenant il faut automatiser le lancement de la commande précédente via udev :
----
root@jeedom:# vi /etc/udev/rules.d99-usb_modeswitch.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="1bbb", ATTRS{idProduct}=="f000", RUN+="/usr/sbin/usb_modeswitch -c /etc/usb_modeswitch.conf"
----

Sous jeedom dans le plugin SMS, il faut (dans mon cas) utiliser le "port SMS" suivant : /dev/ttyUSB3 en gros il faut essayer chaque port pour trouver le bon...

--

[panel,danger]
.J'ai une erreur CME XX
--
Vous pouvez trouver link:http://www.micromedia-int.com/fr/gsm-2/669-cme-error-gsm-equipment-related-errors[ici] la description des differente erreurs CME
--
